# #Ejercicio 1
# GET http://localhost:1234/usuarios/

# #Ejercicio 2
# GET http://localhost:1234/usuarios/2

# #Ejercicio 3
# POST http://localhost:1234/usuarios
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzdWFyaW8iOiJ1c2VyMSIsIm5pdmVsIjoxLCJleHAiOjE2OTgxNTIzMzgyMDEsImlhdCI6MTY5ODE1MTczOH0.qMTLeLV5ABXZUYgNfdf8r4zoHkWsVsk46iknnEBpNWk

# {
#   "dni": "12345678",
#   "nombres": "Nombres de prueba",
#   "apellidos": "apellidos de prueba",
#   "email": "emaildeprueba@gmail.com",
#   "telefono": "12345678",
#   "usuario": "user5",
#   "password": "psw5",
#   "nivel": 3
# }

#Ejercico 4

PATCH http://localhost:1234/usuarios/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzdWFyaW8iOiJ1c2VyMSIsIm5pdmVsIjoxLCJleHAiOjE2OTgxNTc5MTQ0MDksImlhdCI6MTY5ODE1NzMxNH0.FonmRIzUF5hEU8sIqypj-qCxtgfb5rHSSXpBXP1osFU

 {
     "nombres": "Fernando",
     "apellidos" : "Alonso",
     "email" : "fernando.alonso@f1.com"
     
 }

#  #Ejercicio 5
# DELETE http://localhost:1234/usuarios/5
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzdWFyaW8iOiJ1c2VyMSIsIm5pdmVsIjoxLCJleHAiOjE2OTgxNTE1ODUxNDcsImlhdCI6MTY5ODE1MDk4NX0.YOI0FHoWaCZmsS-jC7s-er_SmFnNliiZwmP3CzqmDN8

# #Ejercicio 6
#GET http://localhost:1234/productos/precio/2

# #Ejercicio 7
#GET http://localhost:1234/productos/nombre/2

# # Ejercicio 8
#GET http://localhost:1234/usuarios/telefono/1

# #Ejercicio 9
#GET http://localhost:1234/usuarios/nombre/1

# #Ejercicio 10
#GET http://localhost:1234/productos/stock

# POST http://localhost:1234/auth
# Content-Type: application/json

# {
#    "usuario": "user1",
#    "password": "psw1"
# }